[{$oViewConf->rs_cookiemanager_getCode(2)}]
[{if $oViewConf->rs_cookiemanager_showPopup()}]
    [{include file="rs/cookiemanager/views/tpl/rs_cookie_manager_popup" display=true}]
[{else}]
    [{include file="rs/cookiemanager/views/tpl/rs_cookie_manager_popup" display=false}]
[{/if}]
